// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicoOnlineBusiness.bases.contexto;

namespace ServicoOnlineBusiness.Migrations
{
    [DbContext(typeof(ServicoContexto))]
    partial class ServicoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("db")
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServicoOnlineBusiness.pagamento.dominio.entidade.PagamentoDominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("4d4822f3-78a4-4ae4-95f5-4d312f36fae0"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasDefaultValue("DHR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("AT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(12);

                    b.HasKey("Id");

                    b.ToTable("Pagamento","db");
                });

            modelBuilder.Entity("ServicoOnlineBusiness.pagamento.dominio.entidade.PagamentoItemDominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("10652d6f-6d06-4d4a-9cf6-066d0422ed69"));

                    b.Property<Guid>("PagamentoDominioId");

                    b.Property<int>("Quantidade");

                    b.Property<int>("ServicoDominioId");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("AT");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoDominioId");

                    b.HasIndex("ServicoDominioId");

                    b.ToTable("PagamentoItem","db");
                });

            modelBuilder.Entity("ServicoOnlineBusiness.servico.dominio.entidade.ServicoDominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000);

                    b.Property<string>("Indicacao")
                        .HasMaxLength(150);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("Preco");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("AT");

                    b.Property<int>("tipoServicoDominioId");

                    b.HasKey("Id");

                    b.HasIndex("tipoServicoDominioId");

                    b.ToTable("Servico","db");
                });

            modelBuilder.Entity("ServicoOnlineBusiness.tiposervico.dominio.entidade.TipoServicoDominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasMaxLength(500);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("AT");

                    b.Property<string>("caminhoDaImage")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("TipoServico","db");
                });

            modelBuilder.Entity("ServicoOnlineBusiness.pagamento.dominio.entidade.PagamentoItemDominio", b =>
                {
                    b.HasOne("ServicoOnlineBusiness.pagamento.dominio.entidade.PagamentoDominio", "PagamentoDominio")
                        .WithMany("PagamentoItemDominios")
                        .HasForeignKey("PagamentoDominioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ServicoOnlineBusiness.servico.dominio.entidade.ServicoDominio", "ServicoDominio")
                        .WithMany("PagamentoItemDominios")
                        .HasForeignKey("ServicoDominioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ServicoOnlineBusiness.servico.dominio.entidade.ServicoDominio", b =>
                {
                    b.HasOne("ServicoOnlineBusiness.tiposervico.dominio.entidade.TipoServicoDominio", "tipoServicoDominio")
                        .WithMany("servicoDominios")
                        .HasForeignKey("tipoServicoDominioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
