// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicoOnlineUsuario.empresa.contexto;

namespace ServicoOnlineUsuario.Migrations
{
    [DbContext(typeof(EmpresaContexto))]
    [Migration("20180717153506_InitialEmpresa")]
    partial class InitialEmpresa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServicoOnlineUsuario.empresa.dominio.entidade.CaminhoArquivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaminhoBaseDownload")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("CaminhoBaseImagem")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("EmpresaId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("AT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasName("EmpresaIdIndex");

                    b.ToTable("CaminhoArquivo","dbo");
                });

            modelBuilder.Entity("ServicoOnlineUsuario.empresa.dominio.entidade.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("8411b844-84eb-46c8-abc9-c358fa3ca74f"));

                    b.Property<string>("CnpjCpf");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("AT");

                    b.HasKey("Id");

                    b.ToTable("Empresa","dbo");
                });

            modelBuilder.Entity("ServicoOnlineUsuario.empresa.dominio.entidade.EmpresaUsuario", b =>
                {
                    b.Property<Guid>("EmpresaId");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("AT");

                    b.HasKey("EmpresaId", "UsuarioId")
                        .HasName("PK_EmpresaUsuario");

                    b.HasIndex("EmpresaId")
                        .HasName("EmpresaIdIndex");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasName("UsuarioIdIndex");

                    b.ToTable("EmpresaUsuario","dbo");
                });

            modelBuilder.Entity("ServicoOnlineUsuario.empresa.dominio.entidade.CaminhoArquivo", b =>
                {
                    b.HasOne("ServicoOnlineUsuario.empresa.dominio.entidade.Empresa", "Empresa")
                        .WithOne("CaminhoArquivo")
                        .HasForeignKey("ServicoOnlineUsuario.empresa.dominio.entidade.CaminhoArquivo", "EmpresaId")
                        .HasConstraintName("FK_CaminhoArquivo_Empresa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ServicoOnlineUsuario.empresa.dominio.entidade.EmpresaUsuario", b =>
                {
                    b.HasOne("ServicoOnlineUsuario.empresa.dominio.entidade.Empresa", "Empresa")
                        .WithMany("EmpresaUsuarios")
                        .HasForeignKey("EmpresaId")
                        .HasConstraintName("FK_EmpresaUsuario_Empresa")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
